version: "3.9"

services:
  promethaimem:
    networks:
      - promethai_mem_backend
    build:
      context: ./
    volumes:
      - "./:/app"
    environment:
      - HOST=0.0.0.0
    profiles: ["exclude-from-up"] # Use `docker-compose run teenage-agi` to get an attached container
    ports:
      - 8000:8000
      - 443:443



networks:
  agi_backend:
    name: promethai_mem_backend
